#!/bin/bash

# Directory setup
INPUT_DIR="input"
OUTPUT_DIR="outputs"
DOCS_DIR="docs"

# Create outputs and docs directory if they don't exist
mkdir -p "$OUTPUT_DIR"
mkdir -p "$DOCS_DIR"

echo "========================================================"
echo "🚀 STARTING COMPREHENSIVE HOMILETIC ANALYSIS"
echo "========================================================"

# Iterate over all .txt files in the input directory
for input_file in "$INPUT_DIR"/*.txt; do
    if [ ! -f "$input_file" ]; then
        echo "No input files found in $INPUT_DIR"
        exit 1
    fi

    # Extract base name (filename without extension)
    filename=$(basename -- "$input_file")
    base_name="${filename%.*}"

    echo ""
    echo "--------------------------------------------------------"
    echo "📄 Processing: $base_name"
    echo "--------------------------------------------------------"

    # --- 1. Aristoteles Analysis ---
    target_file="$DOCS_DIR/${base_name}_aristoteles.json"
    if [ -f "$target_file" ]; then
        echo "⏭️  Aristoteles Analysis already exists in $DOCS_DIR. Skipping..."
    else
        echo "🏛️  Running Aristoteles Analysis..."
        ./analyze_aristoteles.py --input "$input_file" --no-summary
        
        # Move output
        # Find the most recent output file for this analysis
        latest_output=$(ls -t "$OUTPUT_DIR"/${base_name}_aristoteles_*.json 2>/dev/null | head -n 1)
        if [ -n "$latest_output" ]; then
            mv "$latest_output" "$target_file"
            echo "✅ Saved to: $target_file"
        else
            echo "❌ Aristoteles analysis failed or no output found."
        fi
    fi

    # --- 2. Kolb Analysis ---
    target_file="$DOCS_DIR/${base_name}_kolb.json"
    if [ -f "$target_file" ]; then
        echo "⏭️  Kolb Analysis already exists in $DOCS_DIR. Skipping..."
    else
        echo "🔍 Running Kolb Analysis..."
        ./analyze_kolb_cyclus.py --input "$input_file" --no-summary
        
        # Move output
        latest_output=$(ls -t "$OUTPUT_DIR"/${base_name}_kolb_*.json 2>/dev/null | head -n 1)
        if [ -n "$latest_output" ]; then
            mv "$latest_output" "$target_file"
            echo "✅ Saved to: $target_file"
        else
            echo "❌ Kolb analysis failed or no output found."
        fi
    fi

    # --- 3. Dekker Analysis ---
    target_file="$DOCS_DIR/${base_name}.json"
    if [ -f "$target_file" ]; then
        echo "⏭️  Dekker Analysis already exists in $DOCS_DIR. Skipping..."
    else
        echo "✝️  Running Dekker Analysis..."
        # Note: analyze_sermon_dekker.py outputs as [basename]_[timestamp].json, NO suffix like _dekker in the filename generated by the python script itself.
        ./analyze_sermon_dekker.py --input "$input_file" 
        
        # Use grep -v to exclude other types to identify the correct file
        latest_output=$(ls -t "$OUTPUT_DIR"/${base_name}_*.json 2>/dev/null | grep -v "_aristoteles_" | grep -v "_kolb_" | grep -v "_schulz_von_thun_" | head -n 1)
        
        if [ -n "$latest_output" ]; then
            mv "$latest_output" "$target_file"
            echo "✅ Saved to: $target_file"
        else
            echo "❌ Dekker analysis failed or no output found."
        fi
    fi

    # --- 4. Schulz von Thun Analysis ---
    target_file="$DOCS_DIR/${base_name}_schulz_von_thun.json"
    if [ -f "$target_file" ]; then
        echo "⏭️  Schulz von Thun Analysis already exists in $DOCS_DIR. Skipping..."
    else
        echo "📡 Running Schulz von Thun Analysis..."
        ./analyze_schulz_von_thun.py --input "$input_file" --no-summary
        
        # Move output
        latest_output=$(ls -t "$OUTPUT_DIR"/${base_name}_schulz_von_thun_*.json 2>/dev/null | head -n 1)
        if [ -n "$latest_output" ]; then
            mv "$latest_output" "$target_file"
            echo "✅ Saved to: $target_file"
        else
            echo "❌ Schulz von Thun analysis failed or no output found."
        fi
    fi

    # --- 5. Transactional Analysis (TA) ---
    target_file="$DOCS_DIR/${base_name}_transactional.json"
    if [ -f "$target_file" ]; then
        echo "⏭️  Transactional Analysis already exists in $DOCS_DIR. Skipping..."
    else
        echo "🧠 Running Transactional Analysis..."
        ./analyze_transactional.py --input "$input_file" --no-summary
        
        # Move output
        latest_output=$(ls -t "$OUTPUT_DIR"/${base_name}_transactional_*.json 2>/dev/null | head -n 1)
        if [ -n "$latest_output" ]; then
            mv "$latest_output" "$target_file"
            echo "✅ Saved to: $target_file"
        else
            echo "❌ Transactional analysis failed or no output found."
        fi
    fi

done

echo ""
echo "========================================================"
echo "🎉 ALL ANALYSES COMPLETED!"
echo "========================================================"