#!/bin/bash

# Directory setup
INPUT_DIR="input"
OUTPUT_DIR="outputs"
DOCS_DIR="docs"

# Create outputs and docs directory if they don't exist
mkdir -p "$OUTPUT_DIR"
mkdir -p "$DOCS_DIR"

echo "========================================================"
echo "🚀 STARTING COMPREHENSIVE HOMILETIC ANALYSIS"
echo "========================================================"

# Iterate over all .txt files in the input directory
for input_file in "$INPUT_DIR"/*.txt; do
    if [ ! -f "$input_file" ]; then
        echo "No input files found in $INPUT_DIR"
        exit 1
    fi

    # Extract base name (filename without extension)
    filename=$(basename -- "$input_file")
    base_name="${filename%.*}"

    echo ""
    echo "--------------------------------------------------------"
    echo "📄 Processing: $base_name"
    echo "--------------------------------------------------------"

    # --- 1. Aristoteles Analysis ---
    echo "🏛️  Running Aristoteles Analysis..."
    ./analyze_aristoteles.py --input "$input_file" --no-summary
    
    # Move output
    # Find the most recent output file for this analysis
    latest_output=$(ls -t "$OUTPUT_DIR"/${base_name}_aristoteles_*.json 2>/dev/null | head -n 1)
    if [ -n "$latest_output" ]; then
        target_file="$DOCS_DIR/${base_name}_aristoteles.json"
        mv "$latest_output" "$target_file"
        echo "✅ Saved to: $target_file"
    else
        echo "❌ Aristoteles analysis failed or no output found."
    fi

    # --- 2. Kolb Analysis ---
    echo "🔍 Running Kolb Analysis..."
    ./analyze_kolb_cyclus.py --input "$input_file" --no-summary
    
    # Move output
    latest_output=$(ls -t "$OUTPUT_DIR"/${base_name}_kolb_*.json 2>/dev/null | head -n 1)
    if [ -n "$latest_output" ]; then
        target_file="$DOCS_DIR/${base_name}_kolb.json"
        mv "$latest_output" "$target_file"
        echo "✅ Saved to: $target_file"
    else
        echo "❌ Kolb analysis failed or no output found."
    fi

    # --- 3. Dekker Analysis ---
    echo "✝️  Running Dekker Analysis..."
    # Note: analyze_sermon_dekker.py outputs as [basename]_[timestamp].json, NO suffix like _dekker in the filename generated by the python script itself.
    # We need to be careful to identify it correctly.
    ./analyze_sermon_dekker.py --input "$input_file" # This script doesn't seem to have --no-summary argument based on argparse code, but let's check if it prints summary. It prints logs.
    
    # The dekker script saves as {base_name}_{timestamp}.json
    # This pattern is generic. However, since we just ran it, it should be the newest file matching that pattern *that isn't* one of the others.
    # BUT, wait. analyze_sermon_dekker.py saves to `outputs/{base_name}_{timestamp}.json`.
    # Other scripts save to `outputs/{base_name}_{type}_{timestamp}.json`.
    # So we can look for a file that does NOT have `_aristoteles`, `_kolb`, or `_schulz` in it.
    
    # A safer way might be to look for the most recent file in outputs directory that matches the basename and has created just now.
    # But let's assume the naming convention holds.
    
    # Use grep -v to exclude other types
    latest_output=$(ls -t "$OUTPUT_DIR"/${base_name}_*.json 2>/dev/null | grep -v "_aristoteles_" | grep -v "_kolb_" | grep -v "_schulz_von_thun_" | head -n 1)
    
    if [ -n "$latest_output" ]; then
        # Check if the file was actually created recently (e.g. in the last minute) to avoid picking up old stale files?
        # For now, just trust the order.
        target_file="$DOCS_DIR/${base_name}.json" # Dekker analysis is the "default" so it maps to the base json name in existing index.html logic?
        # Actually index.html logic:
        # loadExample(baseName) -> loads baseName.txt and baseName.json (Dekker)
        # So yes, Dekker output should be named [baseName].json
        mv "$latest_output" "$target_file"
        echo "✅ Saved to: $target_file"
    else
        echo "❌ Dekker analysis failed or no output found."
    fi

    # --- 4. Schulz von Thun Analysis ---
    echo "📡 Running Schulz von Thun Analysis..."
    ./analyze_schulz_von_thun.py --input "$input_file" --no-summary
    
    # Move output
    latest_output=$(ls -t "$OUTPUT_DIR"/${base_name}_schulz_von_thun_*.json 2>/dev/null | head -n 1)
    if [ -n "$latest_output" ]; then
        target_file="$DOCS_DIR/${base_name}_schulz_von_thun.json"
        mv "$latest_output" "$target_file"
        echo "✅ Saved to: $target_file"
    else
        echo "❌ Schulz von Thun analysis failed or no output found."
    fi

done

echo ""
echo "========================================================"
echo "🎉 ALL ANALYSES COMPLETED!"
echo "========================================================"
